name: Docker Image CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:

  test:
    name: Python unit test to check app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with Pytest
        run: pytest

  dev_build:
    name: build docker image for beta/dev release
    if: github.event.ref == 'refs/heads/dev'
    needs: test
    environment:
      name: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          echo "build and release for ${{ vars.ENVIRONMENT }} environment"
          docker build . --file Dockerfile --tag fast-app:$(date +%s) --tag fast-app:0.0.1-dev

  prod_build:
    name: build docker image for prod release
    if: github.event.ref == 'refs/heads/main'
    needs: test
    environment:
      name: prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          echo "build and release for ${{ vars.ENVIRONMENT }} environment"
          docker build . --file Dockerfile --tag fast-app:$(date +%s) --tag fast-app:0.0.1 --tag fast-app:latest