name: Docker Image CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:

  test:
    name: Python unit test to check app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with Pytest
        run: pytest

  dev_build_dockerhub:
    name: build docker image for beta/dev release
    if: github.event.ref == 'refs/heads/dev'
    needs: test
    environment:
      name: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Automatic tagging of dev release
        id: increment-git-tag
        run:
          bash ./tagging/dev_git_tagging.sh -v patch

      - name: create github tag for dev release
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.increment-git-tag.outputs.git-tag }}
          tag_exists_error: false
          message: "release ${{ steps.increment-git-tag.outputs.git-tag }}"

      # Print result using the env variable.
      - run: |
          echo "Tag already present: ${{ env.TAG_EXISTS }}"
      # Print result using the action output.
      - run: |
          echo "Tag already present: ${{ steps.tag_create.outputs.tag_exists }}"

      - name: build and push docker image to docker registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ahmadalsajid/fast-app:${{ steps.increment-git-tag.outputs.git-tag }}

  #       # Build docker to push to AWS ECS, will work on later
  #      - name: Build the Docker image
  #        env:
  #          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}-dev
  #        run: |
  #          echo "build and release for ${{ vars.ENVIRONMENT }} environment"
  #          docker build . --file Dockerfile --tag fast-app:$(date +%s) --tag fast-app:$IMAGE_TAG

  prod_build:
    name: build docker image for prod release
    if: github.event.ref == 'refs/heads/main'
    needs: test
    environment:
      name: prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          echo "build and release for ${{ vars.ENVIRONMENT }} environment"
          docker build . --file Dockerfile --tag fast-app:$(date +%s) --tag fast-app:0.0.1 --tag fast-app:latest